# Generated by Django 5.0.1 on 2024-02-03 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='profilebio',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='profilephoto',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
